// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/listen-lavender/goseq/model (interfaces: SoftSegmentDao)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSoftSegmentDao is a mock of SoftSegmentDao interface
type MockSoftSegmentDao struct {
	ctrl     *gomock.Controller
	recorder *MockSoftSegmentDaoMockRecorder
}

// MockSoftSegmentDaoMockRecorder is the mock recorder for MockSoftSegmentDao
type MockSoftSegmentDaoMockRecorder struct {
	mock *MockSoftSegmentDao
}

// NewMockSoftSegmentDao creates a new mock instance
func NewMockSoftSegmentDao(ctrl *gomock.Controller) *MockSoftSegmentDao {
	mock := &MockSoftSegmentDao{ctrl: ctrl}
	mock.recorder = &MockSoftSegmentDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSoftSegmentDao) EXPECT() *MockSoftSegmentDaoMockRecorder {
	return m.recorder
}

// CAS mocks base method
func (m *MockSoftSegmentDao) CAS(arg0 context.Context, arg1 uint16, arg2 uint64) (uint64, bool, error) {
	ret := m.ctrl.Call(m, "CAS", arg0, arg1, arg2)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CAS indicates an expected call of CAS
func (mr *MockSoftSegmentDaoMockRecorder) CAS(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CAS", reflect.TypeOf((*MockSoftSegmentDao)(nil).CAS), arg0, arg1, arg2)
}
