# this is a toml document. boom
[app]
    name = "seq"
    mode = "dev"
    debug = false

[server]
    grpc = true
    host = "0.0.0.0:8091"

[mongo_seq]
    addr = "mongodb://127.0.0.1:27017/admin"
    authdb = "workchat"
    authuser = "user"
    authpass = "123456"
    db = "workchat"
    readtimeout = "5000ms"
    writetimeout = "5s"