// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.2.0
// source: seq/seq.proto

package pbseq

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *GetSeqReq) Reset() {
	*x = GetSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_seq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeqReq) ProtoMessage() {}

func (x *GetSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_seq_seq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeqReq.ProtoReflect.Descriptor instead.
func (*GetSeqReq) Descriptor() ([]byte, []int) {
	return file_seq_seq_proto_rawDescGZIP(), []int{0}
}

func (x *GetSeqReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetSeqRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Seq       uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Ts        int64  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	ErrorCode uint32 `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Msg       string `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GetSeqRes) Reset() {
	*x = GetSeqRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_seq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeqRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeqRes) ProtoMessage() {}

func (x *GetSeqRes) ProtoReflect() protoreflect.Message {
	mi := &file_seq_seq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeqRes.ProtoReflect.Descriptor instead.
func (*GetSeqRes) Descriptor() ([]byte, []int) {
	return file_seq_seq_proto_rawDescGZIP(), []int{1}
}

func (x *GetSeqRes) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetSeqRes) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetSeqRes) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *GetSeqRes) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GetSeqRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_seq_seq_proto protoreflect.FileDescriptor

var file_seq_seq_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x71, 0x2f, 0x73, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x73, 0x65, 0x71, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x73,
	0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x29, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x7c, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x36, 0x0a, 0x0a, 0x53, 0x65, 0x71,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x71, 0x12, 0x0e, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x52, 0x65,
	0x71, 0x1a, 0x0e, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x52, 0x65,
	0x73, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x2d, 0x6c, 0x61, 0x76, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2f,
	0x67, 0x6f, 0x73, 0x65, 0x71, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x73, 0x65, 0x71, 0x3b,
	0x70, 0x62, 0x73, 0x65, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seq_seq_proto_rawDescOnce sync.Once
	file_seq_seq_proto_rawDescData = file_seq_seq_proto_rawDesc
)

func file_seq_seq_proto_rawDescGZIP() []byte {
	file_seq_seq_proto_rawDescOnce.Do(func() {
		file_seq_seq_proto_rawDescData = protoimpl.X.CompressGZIP(file_seq_seq_proto_rawDescData)
	})
	return file_seq_seq_proto_rawDescData
}

var file_seq_seq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_seq_seq_proto_goTypes = []interface{}{
	(*GetSeqReq)(nil), // 0: seq.GetSeqReq
	(*GetSeqRes)(nil), // 1: seq.GetSeqRes
}
var file_seq_seq_proto_depIdxs = []int32{
	0, // 0: seq.SeqService.GetSeq:input_type -> seq.GetSeqReq
	1, // 1: seq.SeqService.GetSeq:output_type -> seq.GetSeqRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seq_seq_proto_init() }
func file_seq_seq_proto_init() {
	if File_seq_seq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seq_seq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_seq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSeqRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seq_seq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seq_seq_proto_goTypes,
		DependencyIndexes: file_seq_seq_proto_depIdxs,
		MessageInfos:      file_seq_seq_proto_msgTypes,
	}.Build()
	File_seq_seq_proto = out.File
	file_seq_seq_proto_rawDesc = nil
	file_seq_seq_proto_goTypes = nil
	file_seq_seq_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SeqServiceClient is the client API for SeqService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SeqServiceClient interface {
	GetSeq(ctx context.Context, in *GetSeqReq, opts ...grpc.CallOption) (*GetSeqRes, error)
}

type seqServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeqServiceClient(cc grpc.ClientConnInterface) SeqServiceClient {
	return &seqServiceClient{cc}
}

func (c *seqServiceClient) GetSeq(ctx context.Context, in *GetSeqReq, opts ...grpc.CallOption) (*GetSeqRes, error) {
	out := new(GetSeqRes)
	err := c.cc.Invoke(ctx, "/seq.SeqService/GetSeq", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeqServiceServer is the server API for SeqService service.
type SeqServiceServer interface {
	GetSeq(context.Context, *GetSeqReq) (*GetSeqRes, error)
}

// UnimplementedSeqServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSeqServiceServer struct {
}

func (*UnimplementedSeqServiceServer) GetSeq(context.Context, *GetSeqReq) (*GetSeqRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeq not implemented")
}

func RegisterSeqServiceServer(s *grpc.Server, srv SeqServiceServer) {
	s.RegisterService(&_SeqService_serviceDesc, srv)
}

func _SeqService_GetSeq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeqReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeqServiceServer).GetSeq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seq.SeqService/GetSeq",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeqServiceServer).GetSeq(ctx, req.(*GetSeqReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SeqService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seq.SeqService",
	HandlerType: (*SeqServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSeq",
			Handler:    _SeqService_GetSeq_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seq/seq.proto",
}
